### ISSUE TITLE
Add support for optional and peer dependencies

### ISSUE THREAD

**Issue by RhodeHummel** [JoshuaKGoldberg/package-build-order#10]
The current library only supports calculating the build order using dependencies or devDependencies.

For example:
- `app` has `libraryA` as a dependency
- `app` has `libraryB` as a dependency
- `libraryA` has `libraryB` as a peerDependency
- Therefore we need to build `libraryB` first before building `libraryA` or `app`

Currently this scenario produces a build error since libraryB is a peerDependency.

**Comment by JoshuaKGoldberg** [comment]
Certainly, that would be a great feature add. Thanks for filing @RhodeHummel!

Out of curiosity, may I ask what your use case for this package is? I haven't touched it in a while so I'm just curious. 😄

**Comment by RhodeHummel** [comment]
Sorry I had to recreate the PR since the commit was using a work email. I'm using this with npm@7 workspaces to calculate what workspace to build first. Since this isn't built into npm@7 we need to do the calculation ourselves. Once I figure out the order I can then go in and run `npm run build` in each workspace.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the contribution @RhodeHummel! This should be available now as `0.3.0`. Please let me know if not!

Also, since this repository's tooling is a little crusty _(Gulp! TSLint)_ I filed a couple of issues to clean it up: #12, #13. Let me know if you'd like those done for you to make your life easier. 😄
